org: storyteller
app: aws-textract-task
service: aws-textract-task

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - s3:PutObject
        - s3:GetObject
      Resource: "*"

resources:
  Resources:
    FilesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: FilesTable
        AttributeDefinitions:
          - AttributeName: file_id
            AttributeType: S
        KeySchema:
          - AttributeName: file_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        StreamSpecification:
          StreamViewType: NEW_IMAGE

    MyS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: FilesForTextract

functions:
  get_textract_info:
    handler: handler.get_textract_info
    events:
      - http:
          path: /files/{file_id}
          method: get

  create_file:
    handler: handler.create_file
    events:
      - http:
          path: /files
          method: post

  process_file:
    handler: handler.process_file
    events:
      - s3:
          bucket: FilesForTextract
          event: s3:ObjectCreated:POST

  make_callback:
    handler: handler.make_callback
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - FilesTable
              - StreamArn
